version: 2.1

defaults: &defaults
  docker:
      - image: node:10

workflows:
  version: 2
  build:
    jobs:
      - build:
         filters:
           branches:
             only: /.*/
           tags:
             only: /.*/
      - publish:
         requires: [ 'build_and_test' ]
         context: ci-write
         filters:
           branches:
             only: master

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
         name: build_and_test
         command: |
           npm ci
           npm run test
      - persist_to_workspace:
          root: ../
          paths: [./*]
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
         name: publish
         command: |
           curl -sSf -u$ARTIFACTORY_USER:$ARTIFACTORY_PASS $ARTIFACTORY_NPM_URL -o .npmrc
           npm publish